routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/register','CheckController@register')->name('register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//logout
Route::get('admin/logout','CheckController@logout')->name('logout');



Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');


});

//Frontend
//trang chủ
Route::get('/trang-chu','FrontEndController@TrangChu')->name('trangchu');
Route::get('/trang-chu/chi-tiet/{id}','FrontEndController@chitiet')->name('details_post');
//veLTC
Route::get('/Ve-LTC','FrontEndController@Ve_LTC')->name('Ve-LTC');
//Tin tức
Route::get('/tin-tuc','FrontEndController@TinTuc')->name('tintuc');
Route::get('/tin-tuc/loại-tin/{id}','FrontEndController@show_subcategory')->name('lt_bv');

//kien thuc
Route::get('/kien-thuc','FrontEndController@KienThuc')->name('kienthuc');
//Route::get('/kien-thuc/loại-tin/{id}','KienThucController@KienThuc')->name('KT_KienThuc');
Route::get('/kien-thuc/loại-tin/{id}','KienThucController@show_kienthuc')->name('KT');
Route::post('/xem-them','KienThucController@load_kienthuc')->name('load_kienthuc');

//noi bat
Route::get('/noi-bat','FrontEndController@NoiBat')->name('noibat');
//Route::get('/noi-bat/xem-them','FrontEndController@loadPost')->name('load');

//Route::get('index','TestController@index')->name('index');
Route::post('load_more_data','KienThucController@load_more')->name('load_more_data');

//OTC
Route::get('/OTC','FrontEndController@OTC')->name('OTC');
Route::get('/tim-kiem','FrontEndController@timkiem')->name('timkiem');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = false;
    protected $fillable = ['name','slug','active'];

    public function subcategory(){
        return $this->hasMany('App\Subcategory');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Menu\CreateFormRequest;
use Illuminate\Http\Request;
use Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Category::all();
        return view('BE.category.index',[
            'data'=>$data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('BE.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $request->validate([
//            'name'=>'require|max:255',
//
//            ],[
//            'name.require'=>'vui lòng nhập tên danh mục'
//        ]);
//        $validator = Validator::make(array([)]),
//
//                                         [
//            'name' => 'required|unique:posts|max:255',
//
//        ]);

//        if ($validator->fails()) {
//            return redirect('BE.category.create')
//                ->withErrors($validator)
//                ->withInput();
//        }
        $name = $request->input('name');
        $slug = $request->input('slug');
        $active = $request->input('active');

        $category = new Category();
        $category->name = $name;
        $category->slug = $slug;
        $category->active = $active;

        $category->save();

        session()->flash('success','Tạo thành công.');

        return redirect()->route('admin.category.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit =Category:: find($id);
        return view('BE.category.edit',[
            'edit'=>$edit
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->input('name');
        $slug = $request->input('slug');
        $active = $request->input('active');

        $category =Category::find($id);
        $category->name = $name;
        $category->slug = $slug;
        $category->active = $active;

        $category->save();

        session()->flash('success','Cập nhập thành công.');

        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = Category::destroy($id);

        if ($isDelete) {
            return response()->json(['success' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['success' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/category/create.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm thông tin danh mục <a href="{{route('admin.category.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách danh mục</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Thêm thông tin danh mục</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin danh mục</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.category.store')}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập tên danh mục</label>
                                        <input type="text" class="form-control" name ="name" id="name" placeholder="Nhập tên danh mục">
                                        @if ($errors->any())
                                            <div class="alert alert-danger">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Slug</label>
                                        <input type="text" class="form-control" name="slug" id="slug" placeholder="nhập slug">

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Hoạt động</label>
                                        <input type="number" class="form-control" name="active" id="active" placeholder="" min="0" max="1">

                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Tạo</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/BE/category/edit.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Cập thông tin danh mục <a href="{{route('admin.category.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách danh mục</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Cập nhập thông tin danh mục</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Cập nhập thông tin danh mục</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.category.update',['edit'=>$edit->id])}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập tên danh mục mới</label>
                                        <input value="{{$edit->name}}" type="text" class="form-control" name ="name" id="name" placeholder="Nhập tên danh mục">
                                        @if($errors->has('name'))
                                            <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Slug</label>
                                        <input value="{{$edit->slug}}" type="text" class="form-control" name="slug" id="slug" placeholder="nhập slug">

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Hoạt động</label>
                                        <input value="{{$edit->active}}" type="number" class="form-control" name="active" id="active" min="0" max="1">

                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Cập nhập</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/BE/category/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                DANH SÁCH DANH MỤC <a href="{{route('admin.category.create')}}" class="btn bg-purple btn-flat"><i
                        class="fa fa-plus"></i> Thêm</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ </a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header with-border">

                            <h3 class="box-title">Danh Sách </h3>

                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif


                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>Tên</th>
                                    <th>Slug</th>
                                     <th>Trạng thái</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($data as $key=>$category)
                                    <tr class="item-{{$category->id}}">
                                        <td>{{$key+1}}</td>
                                        <td>{{$category->name}}</td>
                                        <td>{{$category->slug}}</td>
                                        <td>{{$category->active==1 ? 'hiển thị' : 'No'}}</td>
                                        <td>
                                            <a href="{{route('admin.category.edit',['edit'=>$category->id])}}"
                                               class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$category->id}}" class="btn btn-danger btn-delete"><i
                                                    class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>


        </section>
        @endsection
        @section('my_js')
            <script type="text/javascript">
                $(document).ready(function () {

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        if (result) {
                            $.ajax({
                                url: 'admin/category/'+id,
                                type: 'DELETE',
                                data: {
                                    id:'id'
                                },
                                dataType: "json",
                                success: function (res) {

                                    if (res.success != 'undefined' && res.success == 1) {
                                        $('.item-'+id).remove();
                                    }
                                    window.location.href = 'admin/category/';
                                },
                                error: function (e) {
                                    console.log(e);
                                }
                            })
                        }
                    });
                });
            </script>

@endsection