routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/register','CheckController@register')->name('register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//logout
Route::get('admin/logout','CheckController@logout')->name('logout');



Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');


});

//Frontend
//trang chủ
Route::get('/trang-chu','FrontEndController@TrangChu')->name('trangchu');
Route::get('/trang-chu/chi-tiet/{id}','FrontEndController@chitiet')->name('details_post');
//veLTC
Route::get('/Ve-LTC','FrontEndController@Ve_LTC')->name('Ve-LTC');
//Tin tức
Route::get('/tin-tuc','FrontEndController@TinTuc')->name('tintuc');
Route::get('/tin-tuc/loại-tin/{id}','FrontEndController@show_subcategory')->name('lt_bv');

//kien thuc
Route::get('/kien-thuc','FrontEndController@KienThuc')->name('kienthuc');
//Route::get('/kien-thuc/loại-tin/{id}','KienThucController@KienThuc')->name('KT_KienThuc');
Route::get('/kien-thuc/loại-tin/{id}','KienThucController@show_kienthuc')->name('KT');
Route::post('/xem-them','KienThucController@load_kienthuc')->name('load_kienthuc');

//noi bat
Route::get('/noi-bat','FrontEndController@NoiBat')->name('noibat');
//Route::get('/noi-bat/xem-them','FrontEndController@loadPost')->name('load');

//Route::get('index','TestController@index')->name('index');
Route::post('load_more_data','KienThucController@load_more')->name('load_more_data');

//OTC
Route::get('/OTC','FrontEndController@OTC')->name('OTC');
Route::get('/tim-kiem','FrontEndController@timkiem')->name('timkiem');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public $timestamps = false;
    protected $fillable = ['title','description','content','image','subcategories_id','hot','highlights','new_posts','active','key_words','posittion','created_at'];

    public function subcategory(){
        return $this->belongsTo("App\Subcategory","subcategories_id");
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Subcategory;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Post::all();
        $data = Post::latest()->paginate(8);
        return view('BE.post.index',[
            'data'=>$data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subcategory = Subcategory::all();
//        dd($subcategory);
        return view('BE.post.create',[
            'subcate'=> $subcategory
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());
        $request->validate([
            'title'=>'required|max:255|unique:posts',
            'subcategories_id'=>'required',
            'hot'=>'required|not_in:0',
            'new_posts'=>'required|not_in:0',
            'highlights'=>'required|not_in:0',
            'description'=>'required',
            'content'=>'required',
            'image'=>'required|image|mines:jpg,png,gif,svg|max: 10000',
            'key_words'=>'required|max:40',
            'active'=>'required|not_in:0',
            'posittion'=>'required|not_in:0'

            ],[
            'title.required'=>'bạn cần nhập tiêu đề',
            'title.unique'=>'tiêu đề đã được sử dụng',
            'subcategories_id.required'=>'bạn cần chọn danh mục bài viết',
            'hot.required'=>'bạn cần chọn tin',
            'new_posts.required'=>'bạn cần chọn tin',
            'highlights.required'=>'bạn cần chọn tin',
            'description.required'=>'bạn cần nhập mô tả',
            'content.required'=>'bạn cần nhập nội dung',
            'image.required'=>'bạn cần chọn hình ảnh cho bài viết',
            'image.image'=>'file cần có dạng jpg,png,gif,svg',
            'key_words.required'=>'bạn cần nhập từ khoá tìm kiếm cho bài viết',
            'posittion.required'=>'bạn cần chọn vị trí'
        ]);
        $title = $request->input('title');
        $subcategories_id = $request->input('subcategories_id');
        $hot = $request->input('hot');
        $highlights = $request->input('highlights');
        $new_posts = $request->input('new_posts');
        $key_words = $request->input('key_words');
        $description = $request->input('description');
        $content = $request->input('content');
        $active = $request->input('active');
        $posittion = $request->input('posittion');


        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'uploads/post/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $post = new Post();
            $post ->title = $title;
            $post->subcategories_id = $subcategories_id;
            $post->hot = $hot;
            $post->highlights = $highlights;
            $post->new_posts = $new_posts;
            $post->key_words = $key_words;
            $post->description = $description;
            $post->content =$content;
            $post->active = $active;
            $post->image = $path_avatar;
            $post->posittion = $posittion;

            $post->save();
            session()->flash('success','Tạo bài viết thành công');
            return redirect()->route('admin.post.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editPost = Post::find($id);
        $subcategory = Subcategory::all();
        return view('BE.post.edit',[
            'editPost'=>$editPost,
            'subcate'=> $subcategory
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        dd($request->all());
        $request->validate([
//            'title'=>'required|max:255|unique:posts',
//            'subcategories_id'=>'required',
//            'hot'=>'required|not_in:0',
//            'new_posts'=>'required|not_in:0',
//            'highlights'=>'required|not_in:0',
//            'description'=>'required',
//            'content'=>'required',
//            'image'=>'required|image|mines:jpg,png,gif,svg|max: 10000',
//            'key_words'=>'required|max:40',
//            'active'=>'required|not_in:0',
//            'posittion'=>'required|not_in:0'

        ],[
//            'title.required'=>'bạn cần nhập tiêu đề',
//            'title.unique'=>'tiêu đề đã được sử dụng',
//            'subcategories_id.required'=>'bạn cần chọn danh mục bài viết',
//            'hot.required'=>'bạn cần chọn tin',
//            'new_posts.required'=>'bạn cần chọn tin',
//            'highlights.required'=>'bạn cần chọn tin',
//            'description.required'=>'bạn cần nhập mô tả',
//            'content.required'=>'bạn cần nhập nội dung',
//            'image.required'=>'bạn cần chọn hình ảnh mới cho bài viết',
//            'image.image'=>'file cần có dạng jpg,png,gif,svg',
//            'key_words.required'=>'bạn cần nhập từ khoá tìm kiếm cho bài viết',
//            'posittion.required'=>'bạn cần chọn vị trí'
        ]);
        $title = $request->input('title');
        $subcategories_id = $request->input('subcategories_id');
        $hot = $request->input('hot');
        $highlights = $request->input('highlights');
        $new_posts = $request->input('new_posts');
        $key_words = $request->input('key_words');
        $description = $request->input('description');
        $content = $request->input('content');
        $active = $request->input('active');
        $posittion = $request->input('posittion');

        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'uploads/post/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $post = Post::find($id);
            $post ->title = $title;
            $post->subcategories_id = $subcategories_id;
            $post->hot = $hot;
            $post->highlights = $highlights;
            $post->new_posts = $new_posts;
            $post->key_words = $key_words;
            $post->description = $description;
            $post->content = $content;
            $post->active = $active;
            $post->image = $path_avatar;
            $post->posittion = $posittion;

            $post->save();

            session()->flash('success','Cập nhập viết thành công');

            return redirect()->route('admin.post.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = Post::destroy($id);

        if ($isDelete) {
            return response()->json(['success' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['success' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/post/create.blade.php
@extends('BE.layout.main')
@section('content')

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm thông tin bài viết <a href="{{route('admin.post.index')}}" class="btn bg-purple "><i
                        class="fa fa-plus"></i> Danh sách bài viết</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> danh sách</a></li>
                <li><a href="#">thêm thông tin bài viết</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin bài viết</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action="{{route('admin.post.store')}}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập tiêu đề bài viết</label>
                                        <input type="text" class="form-control" name="title" id="title"
                                               placeholder="nhập tiêu đề">
                                        @if($errors->has('title'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('title')}}
                                            </label>
                                        @endif
                                    </div>


                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Hình ảnh</label>
                                        <input type="file" id="image" name="image">
                                        <p class="help-block">Example block-level help text here.</p>
                                        @if($errors->has('image'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('image')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1"> Loại tin </label>
                                        <select class="form-control" name="subcategories_id">
                                            <option value="">--Chọn loại tin--</option>
                                            @foreach($subcate as $item)
                                                <option value="{{$item->id}}">{{$item->name}}</option>
                                            @endforeach

                                        </select>
                                        @if($errors->has('subcategories_id'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('subcategories_id')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Tin hot </label>
                                        <select class="form-control" name="hot">
                                            <option value="">--Chọn--</option>
                                            <option value="1">Tin hot</option>
                                            <option value="0">Không</option>
                                        </select>
                                        @if($errors->has('hot'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('hot')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Tin nổi bật </label>
                                        <select class="form-control" name="highlights">
                                            <option value="">--Chọn--</option>
                                            <option value="1">Tin nổi bật</option>
                                            <option value="0">Không</option>
                                        </select>

                                        @if($errors->has('highlights'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('highlights')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Tin tức mới </label>
                                        <select class="form-control" name="new_posts">
                                            <option value="">--Chọn--</option>
                                            <option value="1">Tin mới</option>
                                            <option value="0">Không</option>
                                        </select>

                                        @if($errors->has('new_posts'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('new_posts')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Hoạt động </label>
                                        <select class="form-control" name="active">
                                            <option value="select">--Chọn--</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">No</option>
                                        </select>
                                        @if($errors->has('new_posts'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('new_posts')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Từ khoá tìm kiếm </label>
                                        <input type="text" class="form-control" name="key_words" id="key_words">
                                        @if($errors->has('key_words'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('key_words')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Mô tả ngắn</label>
                                        <textarea type="email" class="form-control" name="description" id="description"></textarea>

                                        @if($errors->has('description'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('description')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Nội dung</label>
                                        <textarea type="email" class="form-control" name="content" id="content"></textarea>

                                        @if($errors->has('content'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('content')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Vị trí </label>
                                        <select class="form-control" name="posittion">
                                            <option value="">--Chọn--</option>
                                            <option value="1">bài viết mới</option>
                                            <option value="0">No</option>
                                        </select>
                                        @if($errors->has('posittion'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('posittion')}}
                                            </label>
                                        @endif
                                    </div>
{{--                                    <div class="checkbox">--}}
{{--                                        <label>--}}
{{--                                            <input type="checkbox" id="remember"> Check me out--}}
{{--                                        </label>--}}
{{--                                    </div>--}}
                                </div>
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Tạo</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </section>


    </div>
@endsection
@section('my_js')
{{--    <script src="backend/ckeditor/ckeditor.js"></script>--}}
<script src="//cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

    <script type="text/javascript">
        $(function () {
            CKEDITOR.replace('ckeditor');
            CKEDITOR.config.pasteFormWordPromptCleanup = true;
            CKEDITOR.config.pasteFormWordRemoveFontStyles = false;
            CKEDITOR.config.pasteFormWordRemoveStyles = false;
            CKEDITOR.config.language = 'vi';
            CKEDITOR.config.htmlEncodeOutput = false;
            CKEDITOR.config.ProcessHTMLEntities = false;
            CKEDITOR.config.entities = false;
            CKEDITOR.config.entities_latin = false;
            CKEDITOR.config.ForceSimpleAmpersand = true;
            CKEDITOR.replace('description',{
                filebrowserBrowseUrl: 'backend/ckfinder/ckfinder.html',
                filebrowserUploadUrl: 'backend/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserWindowWidth: '1000',
                filebrowserWindowHeight: '700'
            });
            CKEDITOR.replace('content',{
                filebrowserBrowseUrl: 'backend/ckfinder/ckfinder.html',
                filebrowserUploadUrl: 'backend/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserWindowWidth: '1000',
                filebrowserWindowHeight: '700'
            });

        });
    </script>
@endsection

resources/views/BE/post/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                DANH SÁCH QUẢN LÝ BÀI VIẾT <a href="{{route('admin.post.create')}}" class="btn bg-purple btn-flat"><i
                        class="fa fa-plus"></i> Thêm</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ </a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Danh Sách bài viết </h3>
                            <select name=" ">
                                <option value="">--Tất cả--</option>
                                <option value="">Tin hot</option>
                                <option value=""> Tin nổi bật</option>
                                <option value=""> Tin mới</option>
                            </select>
                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif
                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Loại tin</th>
                                    <th>Tin hot</th>
                                    <th>Tin nổi bật</th>
                                    <th>Tin mới</th>
                                    <th>Từ khoá</th>
                                    <th>Mô tả</th>
                                    <th>Trạng thái</th>
{{--                                    <th>Vị trí</th>--}}
                                    <th>Ngày tạo</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($data as $key=>$post)
                                    <tr class="item-{{$post->id}}">
                                        <td>{{$key+1}}</td>
                                        <td>{{$post->title}}</td>
                                        <td><img src="{{asset($post->image)}}" width="100px" height="70px"></td>
                                        <td>{{@$post->subcategory->name}}</td>
                                        <td>{{($post->hot == 1) ? 'hot' : 'No' }}</td>
                                        <td>{{($post->highlights == 1) ? 'Nổi bật' : 'No'}}</td>
                                        <td>{{($post->new_posts==1) ? 'Tin mới' : 'No'}}</td>
                                        <td>{{$post->key_words}}</td>
                                        <td>{{strip_tags($post->description)}}</td>
                                        <td>{{($post->active==1) ? 'hiển thị' : 'No'}}</td>
{{--                                        <td>{{($post->posittion==1) ? 'Bài viết mới' : 'No'}}</td>--}}
                                        <td>{{$post->created_at}}</td>
                                        <td>
                                            <a href="{{route('admin.post.edit',['edit'=>$post->id])}}"
                                               class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$post->id}}" class="btn btn-danger btn-delete"><i
                                                    class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{$data->links()}}
                        </div>
                    </div>
                </div>

            </div>

        </section>
        @endsection
        @section('my_js')

            <script type="text/javascript">
                $(document).ready(function () {
                    // Thiết lập csrf => chổng giả mạo
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        // let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        Swal.fire({
                            title: 'Bạn có chắc không?',
                            text: "Bạn có chắc chắn muốn xóa ?",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes'
                        }).then((result) => {
                                if (result.isConfirmed) {
                                    $.ajax({
                                        url: 'admin/post/' + id,
                                        type: 'DELETE',
                                        data: {
                                            name: ''
                                        },
                                        dataType: "json",
                                        success: function (res) {
                                            if (res.success != 'undefined' && res.success == 1) {
                                                $('.item-' + id).remove();
                                                Swal.fire(
                                                    'Deleted!',
                                                    'Xoá thành công',
                                                    'success'
                                                )
                                            }
                                            window.location.reload();
                                        },
                                        error: function (e) {
                                            console.log(e);
                                        }
                                    })
                                }
                            }
                        );

                    });
                });
            </script>

@endsection