routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/register','CheckController@register')->name('register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//logout
Route::get('admin/logout','CheckController@logout')->name('logout');



Route::group(['prefix'=>'admin','as'=>'admin.','middleware' => 'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');


});

//Frontend
//trang chủ
Route::get('/trang-chu','FrontEndController@TrangChu')->name('trangchu');
Route::get('/trang-chu/chi-tiet/{id}','FrontEndController@chitiet')->name('details_post');
//veLTC
Route::get('/Ve-LTC','FrontEndController@Ve_LTC')->name('Ve-LTC');
//Tin tức
Route::get('/tin-tuc','FrontEndController@TinTuc')->name('tintuc');
Route::get('/tin-tuc/loại-tin/{id}','FrontEndController@show_subcategory')->name('lt_bv');

//kien thuc
Route::get('/kien-thuc','FrontEndController@KienThuc')->name('kienthuc');
//Route::get('/kien-thuc/loại-tin/{id}','KienThucController@KienThuc')->name('KT_KienThuc');
Route::get('/kien-thuc/loại-tin/{id}','KienThucController@show_kienthuc')->name('KT');
Route::post('/xem-them','KienThucController@load_kienthuc')->name('load_kienthuc');

//noi bat
Route::get('/noi-bat','FrontEndController@NoiBat')->name('noibat');
//Route::get('/noi-bat/xem-them','FrontEndController@loadPost')->name('load');

//Route::get('index','TestController@index')->name('index');
Route::post('load_more_data','KienThucController@load_more')->name('load_more_data');

//OTC
Route::get('/OTC','FrontEndController@OTC')->name('OTC');
Route::get('/tim-kiem','FrontEndController@timkiem')->name('timkiem');

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    public $timestamps = false;
    protected $fillable = [ 'name','slug','category_id','active','created_at'];

    public function category(){
        return $this->belongsTo('App\category','categories_id');
    }
    public function post(){
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Subcategory;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sub = Subcategory::all();
        $item = Subcategory::latest()->paginate(5);
        return view('BE.subcategory.index',[
            'sub'=>$item
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('BE.subcategory.create',[
            'category'=>$category
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([


           ],[

        ]);
        $name=$request->input('name');
        $categories_id= $request->input('categories_id');
        $active = $request->input('active');

        $subcategory = new Subcategory();
        $subcategory->name = $name;
        $subcategory->categories_id=$categories_id;
        $subcategory->active=$active;
        $subcategory->save();
        session()->flash('success','Tạo danh mục thành công');
        return redirect()->route('admin.subcategory.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::all();
        $edit = Subcategory::find($id);
        return view('BE.subcategory.edit',[
            'edit'=>$edit,
            'category'=>$category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([


        ],[

        ]);
        $name=$request->input('name');
        $categories_id= $request->input('categories_id');
        $active = $request->input('active');

        $subcategory = Subcategory::find($id);
        $subcategory->name = $name;
        $subcategory->categories_id=$categories_id;
        $subcategory->active=$active;
        $subcategory->save();
        session()->flash('success','Cập nhập loại tin thành công');
        return redirect()->route('admin.subcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = Subcategory::destroy($id);

        if ($isDelete) {
            return response()->json(['success' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['success' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/subcategory/create.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm thông tin loại tin <a href="{{route('admin.subcategory.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách loại tin</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Thêm loại tin</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin loại tin</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.subcategory.store')}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập tên loại tin</label>
                                        <input type="text" class="form-control" name ="name" id="name" placeholder="Nhập tên loại tin">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Danh mục</label>
                                        <select class="form-control" name="categories_id">
                                            <option value="select">--Chọn danh mục--</option>
                                            @foreach($category as $category)
                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Hoạt động</label>
                                        <input type="number" class="form-control" name="active" id="active" placeholder="" min="0" max="1">

                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Tạo</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/BE/subcategory/edit.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Chỉnh sửa loại tin <a href="{{route('admin.subcategory.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách loại tin</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Chỉnh sửa loại tin</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin loại tin mới</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action = "{{route('admin.subcategory.update',['edit'=>$edit->id])}}" method = "post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Nhập tên loại tin mới</label>
                                        <input value="{{$edit->name}}" type="text" class="form-control" name ="name" id="name" placeholder="Nhập tên loại tin">
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Chọn Danh mục mới</label>
                                        <select class="form-control" name="categories_id">
                                            <option value="{{$edit->id}}}">--Chọn danh mục--</option>
                                            @foreach($category as $category)
                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Hoạt động</label>
                                        <input value="{{$edit->active}}" type="number" class="form-control" name="active" id="active" placeholder="" min="0" max="1">

                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Cập nhập</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/BE/subcategory/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
               QUẢN LÝ DANH SÁCH LOẠI TIN <a href="{{route('admin.subcategory.create')}}" class="btn bg-purple btn-flat"><i
                        class="fa fa-plus"></i> Thêm Loại Tin</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ </a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header with-border">

                            <h3 class="box-title">Danh Sách </h3>

                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif


                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>Tên</th>
                                    <th>Danh mục</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày tạo</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($sub as $key=>$item)
                                    <tr class="item-{{$item->id}}">
                                        <td>{{$key+1}}</td>
                                        <td>{{$item->name}}</td>
                                        <td>{{@$item->category->name}}</td>
                                        <td>{{$item->active==1 ? 'hiển thị' : 'No'}}</td>
                                        <td>{{$item->created_at}}</td>
                                        <td>
                                            <a href="{{route('admin.subcategory.edit',['edit'=>$item->id])}}"
                                               class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$item->id}}" class="btn btn-danger btn-delete"><i
                                                    class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                        <div class="box-footer clearfix">
                            {{$sub->links()}}
                        </div>
                    </div>
                </div>

            </div>


        </section>
        @endsection
        @section('my_js')
            <script type="text/javascript">
                $(document).ready(function () {

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        if (result) {
                            $.ajax({
                                url: 'admin/subcategory/'+id,
                                type: 'DELETE',
                                data: {
                                    id:'id'
                                },
                                dataType: "json",
                                success: function (res) {

                                    if (res.success != 'undefined' && res.success == 1) {
                                        $('.item-'+id).remove();
                                    }
                                    window.location.href = 'admin/subcategory/';
                                },
                                error: function (e) {
                                    console.log(e);
                                }
                            })
                        }
                    });
                });
            </script>
@endsection